trigger:
  branches:
    include:
      - feature_mllab/*
      - feature/*
      - develop
      - master

resources:
  repositories:
    - repository: ci-tools
      type: git
      name: DAPlatform01/dap-core-ci-tools
      ref: refs/heads/master

pool:
  vmImage: ubuntu-18.04
  #name: RDT Repsol Linux EU - Datahub

steps:

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/*.yml'
    inputs:
      rootDirectory: kubernetes
      targetFiles: '**/*.yml'
      verbosity: detailed
      keepToken: true

  - template: build-push-docker-image.yml@ci-tools

  - task: CopyFiles@2
    displayName: 'Copy Files (kubernetes manifests) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: kubernetes
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
      OverWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Files (grafana datasources configuration) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: configuration/datasources
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: false
      FlattenFolders: true
      OverWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Files (grafana dashboards configuration) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: configuration/dashboards
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: false
      FlattenFolders: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'