trigger:
  branches:
    include:
      - feature/*
      - develop
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/*.yml'
    inputs:
      rootDirectory: kubernetes
      targetFiles: '**/*.yml'
      verbosity: detailed
      keepToken: true

  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: 'Production (IT.EU.Production Common Services)'
      azureContainerRegistry: daplatform0101pcr.azurecr.io
      dockerFile: Dockerfile
      envVars: 
        "GF_INSTALL_PLUGINS=natel-plotly-panel,grafana-piechart-panel"


  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      azureSubscriptionEndpoint: 'Production (IT.EU.Production Common Services)'
      azureContainerRegistry: daplatform0101pcr.azurecr.io
      command: 'Push an image'

  - task: CopyFiles@2
    displayName: 'Copy Files (kubernetes manifests) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: kubernetes
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
      OverWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Files (grafana datasources configuration) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: configuration/datasources
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: false
      FlattenFolders: true
      OverWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Files (grafana dashboards configuration) to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: configuration/dashboards
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: false
      FlattenFolders: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'