trigger:
  branches:
    include:
      - feature/*
      - develop
      - master
      - hotfix/*

  paths:
    exclude:
      - setup.py

resources:
  repositories:
    - repository: ci-tools
      type: git
      name: DAPlatform01/dap-core-ci-tools
      ref: refs/heads/master

pool:
  name: RDT Repsol Linux EU - Datahub

strategy:
  matrix:
    Python36:
      PYTHON_VERSION: '3.6'

variables:
  - group: CIToken
  - group: "sonar8-pro"
  - name: python_version
    value: $(python.version)

steps:

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: "3.6"
  - bash: |
      pip install twine==3.3.0

  - template: twine-authenticate.yml@ci-tools

  - template: pip-authenticate.yml@ci-tools

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/*.yml'
    inputs:
      rootDirectory: kubernetes
      targetFiles: '**/*.yml'
      verbosity: detailed
      keepToken: true

  - template: update-repo-version-python.yml@ci-tools
    parameters:
      repository: $(Build.Repository.Name)
      branch: $(Build.SourceBranch)
      build: $(Build.BuildId)
      token: $(service-token)
      buildLibrary: true
      namespace: $(Namespace)

  - template: build-push-docker-image-proxy.yml@ci-tools

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
