trigger:
  branches:
    include:
      - feature/*
      - develop
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: kubernetes
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true