{
 "title": "Operational Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Llamadas por nivel de log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                           //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                  //this is a macro used to show the full chart’s time range, choose the datetime column here\n| where NIVEL_s == \"ERROR\"\n| summarize count()",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                             //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Listado",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| order by TimeGenerated asc",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "#{LogWorkspaceEnv}# - Operational Logs por UID",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UID",
    "label": "UID",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend uid=extract(\"^(\\\\w+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s)\n| distinct uid"
   }
  ]
 },
 "panels": [
  {
   "title": "Listado de ejecuciones por UID",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend fecha=tostring(parse_json(PAYLOAD_s).DATADATE)\r\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\r\n| where extract(\"^(\\\\w+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\r\n| order by fecha, TimeGenerated desc\n| project FECHA_EJECUCION=TimeGenerated, FECHA_DATO=fecha, MODULO=MODULO_s, STATUS=tostring(parse_json(PAYLOAD_s).STATUS), MSG_ERROR=tostring(parse_json(PAYLOAD_s).MSG_ERROR), UID_s, LOGTYPE=tostring(parse_json(PAYLOAD_s).LOGTYPE)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL         \r                                                \n| where $__timeFilter(TimeGenerated)                                             \n| where NIVEL_s == \"ERROR\" and extract(\"^(\\\\w+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| summarize count()\r\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por nivel de Log",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL                                                          \r\n| where $__timeFilter(TimeGenerated)                                      \n| where extract(\"^(\\\\w+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) \n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL \r\n| where $__timeFilter(TimeGenerated)                                      \n| where extract(\"^(\\\\w+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID) \r\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval)  \r\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "#{LogWorkspaceEnv}# - Operational Logs por application y region",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\n| distinct app"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\n| distinct region"
   }
  ]
 },
 "panels": [
  {
   "title": "Listado de ejecuciones por application y region",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)  \r\n| where $__timeFilter(TimeGenerated)                                      \r\n| where region in ($Region) and app in ($Application)\r\n| order by TimeGenerated asc\r\n| project FECHA_EJECUCION=TimeGenerated, APPLICATION=app, REGION=region, FECHA_DATO=tostring(parse_json(PAYLOAD_s).DATADATE), MODULO=MODULO_s, STATUS=tostring(parse_json(PAYLOAD_s).STATUS), MSG_ERROR=tostring(parse_json(PAYLOAD_s).MSG_ERROR), LOGTYPE=tostring(parse_json(PAYLOAD_s).LOGTYPE)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL         \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)                                                    \n| where $__timeFilter(TimeGenerated)                                             \n| where NIVEL_s == \"ERROR\" and region in ($Region) and app in ($Application) \r\n| summarize count()\r\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por nivel de Log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL                                                          \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\r\n| where $__timeFilter(TimeGenerated)                                      \n| where region in ($Region) and app in ($Application)\r\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) \n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)  \r\n| where $__timeFilter(TimeGenerated)                                      \n| where region in ($Region) and app in ($Application) \r\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval)  \r\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Metadatos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "streaming",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM streaming" }
   ]
  },
  {
   "title": "files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM files" }
   ]
  },
  {
   "title": "schemas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM schemas" }
   ]
  },
  {
   "title": "servicenow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM servicenow" }
   ]
  },
  {
   "title": "db",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * from db" }
   ]
  },
  {
   "title": "salesforce",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "rawSql": "SELECT * FROM salesforce" }
   ]
  },
  {
   "title": "external_apis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "rawSql": "SELECT * FROM external_apis" }
   ]
  },
  {
   "title": "provider",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "rawSql": "SELECT * FROM provider" }
   ]
  },
  {
   "title": "ddg_dwh",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "rawSql": "SELECT * FROM ddg_dwh" }
   ]
  },
  {
   "title": "processor",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "rawSql": "SELECT * FROM processor" }
   ]
  },
  {
   "title": "manual_files_use_cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT * FROM manual_files_use_cases"
    }
   ]
  },
  {
   "title": "process_orchestrator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT * FROM process_orchestrator"
    }
   ]
  },
  {
   "title": "insecure",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "rawSql": "SELECT * FROM insecure" }
   ]
  },
  {
   "title": "internal_apis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "rawSql": "SELECT * FROM internal_apis" }
   ]
  },
  {
   "title": "metadata_schema",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "rawSql": "SELECT * FROM metadata_schema" }
   ]
  },
  {
   "title": "dynamic_dataset_generator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dynamic_dataset_generator"
    }
   ]
  },
  {
   "title": "teradata",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "rawSql": "SELECT * FROM teradata" }
   ]
  },
  {
   "title": "manual_files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "rawSql": "SELECT * FROM manual_files" }
   ]
  }
 ]
}
{
 "title": "Databricks driver logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Listado",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "SparkLoggingEvent_CL\n| where $__timeFilter(TimeGenerated)\n| where logger_name_s contains \"com.repsol.datalake\"\n| where dbWorkspaceName_s == \"#{Namespace}#dbcore\" \n| project TimeGenerated, logger_name_s, Level, Message, dbWorkspaceName_s, clusterName_s, clusterId_s \n| order by TimeGenerated asc",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}