---
apiVersion: v1
kind: Service
metadata:
  namespace: core-monitoring
  name: dap-core-grafana
  labels:
    app: dap-core-grafana
    tier: monitoring
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: dap-core-grafana
    tier: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: core-monitoring
  name: dap-core-grafana
spec:
  selector:
    matchLabels:
      app: dap-core-grafana
      tier: monitoring
  replicas: 1
  template:
    metadata:
      namespace: core-monitoring
      labels:
        app: dap-core-grafana
        tier: monitoring
    spec:
      containers:
        - name: dap-core-grafana-container
          image: daplatform0101pcr.azurecr.io/dap-core-grafana:#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
            name: http
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests: 
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            # - mountPath: /var/lib/grafana
            #   name: grafana-storage
            #   readOnly: false
            - mountPath: /var/lib/grafana/dashboards/core
              name: grafana-core-dashboards
              readOnly: true
            - mountPath: /var/lib/grafana/dashboards/usecases
              name: grafana-usecases-dashboards
              readOnly: true
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: GF_SERVER_DOMAIN
              value: #{Namespace}#akcore.cloudapp.repsol.com
            - name: GF_SERVER_ROOT_URL
              value: https://#{Namespace}#akcore.cloudapp.repsol.com
            - name: GF_SECURITY_ADMIN_USER
              value: #{grafana-admin-user}#
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: #{grafana-admin-password}#
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: Azure AD
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: 'True'
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: 'True'
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: 6ac06a79-9632-43a3-a789-72e3f382848d
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              value: #{grafana-oauth-secret}#
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid email profile
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: https://login.microsoftonline.com/0a25214f-ee52-483c-b96b-dc79f3227a6f/oauth2/v2.0/authorize
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: https://login.microsoftonline.com/0a25214f-ee52-483c-b96b-dc79f3227a6f/oauth2/v2.0/token
            - name: GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS
              value: repsol.com servexternos.repsol.com
      volumes:
        # - name: grafana-storage
        #   emptyDir: {}
        - name: grafana-core-dashboards
          configMap:
            defaultMode: 420
            name: grafana-core-dashboards
        - name: grafana-usecases-dashboards
          configMap:
            defaultMode: 420
            name: grafana-usecases-dashboards
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
---