---
apiVersion: v1
kind: Service
metadata:
  namespace: scc
  name: dap-core-scc-api
  labels:
    app: dap-core-scc-api
    tier: backend
spec:
  ports:
    - port: 80
  selector:
    app: dap-core-scc-api
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: scc
  name: dap-core-scc-api
spec:
  selector:
    matchLabels:
      app: dap-core-scc-api
      tier: backend
  replicas: 1
  template:
    metadata:
      namespace: scc
      labels:
        app: dap-core-scc-api
        tier: backend
    spec:
      containers:
        - name: dap-core-scc-api-container
          image: daplatform0101pcr.azurecr.io/dap-core-scc-api:#{Build.BuildId}#
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: TENANT_ID
              value: #{df-dap-tenant-id}#
            - name: NAMESPACE
              value: #{Namespace}#
            - name: KEY_VAULT_NAME
              value: #{KeyVaultName}#
            - name: KEY_VAULT_CLIENT_ID
              value: #{adapp-kvreader-id}#
            - name: KEY_VAULT_SECRET
              value: #{adsp-kvreader-secret}#
            - name: API_PREFIX
              value: #{api_prefix}#
---