{
 "title": "Operational Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Llamadas por nivel de log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                           //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL        \n| extend payload = parse_json(PAYLOAD_s)\n| extend logtype = tostring(payload.LOGTYPE)\n| extend status = tostring(payload.STATUS)                                                      //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                  //this is a macro used to show the full chart’s time range, choose the datetime column here\n| where logtype in (\"ERROR\", \"END\") and status == \"KO\" \n| summarize count()",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                             //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Listado",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\nCoreOperationLog#{LogWorkspaceEnv}#_CL                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| order by TimeGenerated asc",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Operational Logs por UID",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UID",
    "label": "UID",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend uid=extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s)\n| distinct uid"
   }
  ]
 },
 "panels": [
  {
   "title": "Listado de ejecuciones por UID",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend fecha=tostring(parse_json(PAYLOAD_s).DATADATE)\r\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\r\n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| order by fecha, TimeGenerated desc\n| project FECHA_EJECUCION=TimeGenerated, FECHA_DATO=fecha, MODULO=MODULO_s, STATUS=tostring(parse_json(PAYLOAD_s).STATUS), MSG=tostring(parse_json(PAYLOAD_s).MSG), UID_s, LOGTYPE=tostring(parse_json(PAYLOAD_s).LOGTYPE)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL         \r                                                \n| where $__timeFilter(TimeGenerated)                                             \n| where NIVEL_s == \"ERROR\" and extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| summarize count()\r\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por nivel de Log",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL                                                          \r\n| where $__timeFilter(TimeGenerated)                                      \n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) \n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL \r\n| where $__timeFilter(TimeGenerated)                                      \n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, UID_s) in ($UID)\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval)  \r\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Operational Logs por application y region",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\n| distinct app"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\n| distinct region"
   }
  ]
 },
 "panels": [
  {
   "title": "Listado de ejecuciones por application y region",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)  \r\n| where $__timeFilter(TimeGenerated)                                      \r\n| where region in ($Region) and app in ($Application)\r\n| order by TimeGenerated asc\r\n| project FECHA_EJECUCION=TimeGenerated, APPLICATION=app, REGION=region, FECHA_DATO=tostring(parse_json(PAYLOAD_s).DATADATE), MODULO=MODULO_s, STATUS=tostring(parse_json(PAYLOAD_s).STATUS), MSG=tostring(parse_json(PAYLOAD_s).MSG), LOGTYPE=tostring(parse_json(PAYLOAD_s).LOGTYPE)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL         \r\n| extend payload = parse_json(PAYLOAD_s)\n| extend logtype = tostring(payload.LOGTYPE)\n| extend status = tostring(payload.STATUS)        \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)                                                    \n| where $__timeFilter(TimeGenerated)   \n| where logtype in (\"ERROR\", \"END\") and status == \"KO\"                                           \n| where region in ($Region) and app in ($Application) \n| summarize count()\r\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por nivel de Log",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL                                                          \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\r\n| where $__timeFilter(TimeGenerated)                                      \n| where region in ($Region) and app in ($Application)\r\n| summarize count() by NIVEL_s, bin(TimeGenerated, $__interval) \n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Llamadas por módulo",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL \r\n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\r\n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)  \r\n| where $__timeFilter(TimeGenerated)                                      \n| where region in ($Region) and app in ($Application) \r\n| summarize count() by MODULO_s, bin(TimeGenerated, $__interval)  \r\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Metadatos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "azure_function_apis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.azure_function_apis"
    }
   ]
  },
  {
   "title": "db",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * from dbo.db" }
   ]
  },
  {
   "title": "ddg_dwh",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.ddg_dwh" }
   ]
  },
  {
   "title": "dynamic_dataset_generator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.dynamic_dataset_generator"
    }
   ]
  },
  {
   "title": "files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.files" }
   ]
  },
  {
   "title": "insecure",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.insecure" }
   ]
  },
  {
   "title": "internal_apis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.internal_apis"
    }
   ]
  },
  {
   "title": "manual_files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.manual_files" }
   ]
  },
  {
   "title": "manual_files_use_cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.manual_files_use_cases"
    }
   ]
  },
  {
   "title": "metadata_schema",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.metadata_schema"
    }
   ]
  },
  {
   "title": "mllab",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.mllab" }
   ]
  },
  {
   "title": "process_orchestrator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.process_orchestrator"
    }
   ]
  },
  {
   "title": "processor",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.processor" }
   ]
  },
  {
   "title": "provider",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.provider" }
   ]
  },
  {
   "title": "salesforce",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.salesforce" }
   ]
  },
  {
   "title": "schemas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.schemas" }
   ]
  },
  {
   "title": "servicenow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.servicenow" }
   ]
  },
  {
   "title": "streaming",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.streaming" }
   ]
  },
  {
   "title": "teradata",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.teradata" }
   ]
  },
  {
   "title": "triggers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "rawSql": "SELECT * FROM dbo.triggers" }
   ]
  },
  {
   "title": "process_list_cmdb",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbo.process_list_cmdb"
    }
   ]
  }
 ]
}
{
 "title": "Databricks driver logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Listado",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "SparkLoggingEvent_CL\n| where $__timeFilter(TimeGenerated)\n| where logger_name_s contains \"com.repsol.datalake\"\n| where dbWorkspaceName_s == \"#{Namespace}#dbcore\" \n| project TimeGenerated, logger_name_s, Level, Message, dbWorkspaceName_s, clusterName_s, clusterId_s \n| order by TimeGenerated asc",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Function App Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RoleName",
    "label": "App Function",
    "query": "union\napp('#{Namespace}#fcoprpyai').traces,\napp('#{Namespace}#fiapipyai').traces,\napp('#{Namespace}#fprcspyai').traces,\napp('#{Namespace}#fpricmxai').traces,\napp('#{Namespace}#fvvddjvai').traces,\napp('#{Namespace}#fxapipyai').traces\n| project cloud_RoleName"
   },
   {
    "name": "name",
    "label": "Function Name",
    "query": "union\napp('#{Namespace}#fcorepyai').requests,\napp('#{Namespace}#fcoexpyai').requests,\napp('#{Namespace}#fcopipyai').requests\n| where cloud_RoleName != \"\" and cloud_RoleName in ($RoleName)\n| distinct name"
   }
  ]
 },
 "panels": [
  {
   "title": "Duración por App Function",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "union\napp('#{Namespace}#fcoprpyai').requests,\napp('#{Namespace}#fiapipyai').requests,\napp('#{Namespace}#fprcspyai').requests,\napp('#{Namespace}#fpricmxai').requests,\napp('#{Namespace}#fvvddjvai').requests,\napp('#{Namespace}#fxapipyai').requests\n| where $__timeFilter(timestamp)\n| where name != \"\" and name in ($name)\n| where cloud_RoleName != \"\" and cloud_RoleName in ($RoleName)\n| extend duration_in_seconds = duration/(1000)\n| summarize count() by cloud_RoleName, duration_in_seconds, timestamp\n| order by timestamp desc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Duración por Function Name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "union\napp('#{Namespace}#fcoprpyai').requests,\napp('#{Namespace}#fiapipyai').requests,\napp('#{Namespace}#fprcspyai').requests,\napp('#{Namespace}#fpricmxai').requests,\napp('#{Namespace}#fvvddjvai').requests,\napp('#{Namespace}#fxapipyai').requests\n| where $__timeFilter(timestamp)\n| where name != \"\" and name in ($name)\n| where cloud_RoleName != \"\" and cloud_RoleName in ($RoleName)\n| extend duration_in_seconds = duration/(1000)\n| summarize count() by name, duration_in_seconds, timestamp\n| order by timestamp desc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "union\napp('#{Namespace}#fcoprpyai').requests,\napp('#{Namespace}#fiapipyai').requests,\napp('#{Namespace}#fprcspyai').requests,\napp('#{Namespace}#fpricmxai').requests,\napp('#{Namespace}#fvvddjvai').requests,\napp('#{Namespace}#fxapipyai').requests\n| where $__timeFilter(timestamp)\n| where name != \"\" and name in ($name) and name != \"adfError\"\n| where cloud_RoleName != \"\" and cloud_RoleName in ($RoleName)\n| where resultCode != 200\n| summarize count()",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "union\napp('#{Namespace}#fcoprpyai').traces,\napp('#{Namespace}#fiapipyai').traces,\napp('#{Namespace}#fprcspyai').traces,\napp('#{Namespace}#fpricmxai').traces,\napp('#{Namespace}#fvvddjvai').traces,\napp('#{Namespace}#fxapipyai').traces\n| where $__timeFilter(timestamp)\n| where operation_Name != \"\" and operation_Name in ($name)\n| where cloud_RoleName != \"\" and cloud_RoleName in ($RoleName)\n| project timestamp, message, cloud_RoleName, operation_Name\n| order by timestamp asc ",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "PITagManager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pi_server",
    "label": "pi_server",
    "query": "SELECT pi_server FROM [pitagmanager].[pi_system_servers]\nUNION SELECT pi_server FROM [pitagmanager].[pi_system_tags]\nUNION SELECT pi_server FROM [pitagmanager].[pi_system_executions]\nUNION SELECT pi_server FROM [pitagmanager].[pi_system_enqueues]\nUNION SELECT pi_server FROM [pitagmanager].[pi_system_orders]\nUNION SELECT pi_server FROM  [pitagmanager].[pi_system_piaf]"
   }
  ]
 },
 "panels": [
  {
   "title": "PI Servers",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_servers]\nWHERE pi_server in ($pi_server)"
    }
   ]
  },
  {
   "title": "PI Tags",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_tags]\nWHERE pi_server in ($pi_server)\nORDER BY pi_server"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_executions]\nWHERE pi_server in ($pi_server)\nORDER BY [requested_start_time] DESC"
    }
   ]
  },
  {
   "title": "Enqueues",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_enqueues]\nWHERE pi_server in ($pi_server)"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_orders]\nWHERE pi_server in ($pi_server)\nORDER BY [create_at] DESC"
    }
   ]
  },
  {
   "title": "Order Items",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_order_items]"
    }
   ]
  },
  {
   "title": "PI Ad user groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_ad_user_groups]"
    }
   ]
  },
  {
   "title": "PI Piaf",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT * FROM [pitagmanager].[pi_system_piaf]\nWHERE pi_server in ($pi_server)"
    }
   ]
  }
 ]
}
{
 "title": "Data Quality Overview",
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\n| distinct app"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\n| distinct region"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Data Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend percent_excluded = todouble(cleaner_results.percent_excluded)\r\n| extend logtype = tostring(payload.LOGTYPE)\n| where MODULO_s == \"SANITED\"\r and logtype == \"END\"\n| project  app, percent_excluded, TimeGenerated, datadate\r\n| summarize arg_max(TimeGenerated, *) by app, datadate\r\n| summarize 100 - avg(percent_excluded)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Data Quality Overview By Application And Region",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\n| extend payload = parse_json(PAYLOAD_s)\n| extend region=tostring(payload.REGION)\n| extend app=tostring(payload.APPLICATION)\n| extend datadate=tostring(payload.DATADATE)\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_OUT\n| extend dataset_name = dataset.NAME\n| extend dataset_length = toint(dataset.NUM_ITEMS)\n| extend total_rows_excluded = toint(cleaner_results.total_row_excluded)\n| extend percent_excluded = todouble(cleaner_results.percent_excluded)\n| extend logtype = tostring(payload.LOGTYPE)\n| where MODULO_s == \"SANITED\" and logtype == \"END\"\n| where region in ($Region) and app in ($Application)\n| order by TimeGenerated desc\n| project \nAPPLICATION=app,\nREGION=region,\nDATA_DATE=datadate,\nEXECUTION_DATE=TimeGenerated,\nTOTAL_VALID_ROWS=dataset_length,\nTOTAL_ROWS_EXCLUDED=total_rows_excluded,\nPERCENT_EXCLUDED = percent_excluded",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Overall Data Quality By App And Region",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend percent_excluded = todouble(cleaner_results.percent_excluded)\r\n| extend logtype = tostring(payload.LOGTYPE)\n| where app in ($Application) and region in ($Region)\n| where $__timeFilter(tdatadate)\n| where MODULO_s == \"SANITED\"\r and logtype == \"END\"\n| project  app, percent_excluded, TimeGenerated, datadate\r\n| summarize arg_max(TimeGenerated, *) by app, datadate\r\n| summarize 100-avg(percent_excluded)\n\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Data Quality over Time And Region By App",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend percent_excluded = todouble(cleaner_results.percent_excluded)\r\n| extend logtype = tostring(payload.LOGTYPE)\n| where MODULO_s == \"SANITED\"\r and logtype == \"END\"\n| where region in ($Region) and app in ($Application)\r\n| summarize arg_max(TimeGenerated, *) by app, region, datadate\n| summarize sum(100-percent_excluded) by app, bin(tdatadate, $__interval)\n| sort by tdatadate asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Data Quality Detail",
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "AP_EYP_PI" },
   { "name": "region", "label": "Region", "query": "GLB" },
   {
    "name": "dataset",
    "label": "Dataset",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL \n| extend payload = parse_json(PAYLOAD_s)\n| extend region=tostring(payload.REGION)\n| extend app=tostring(payload.APPLICATION)\n| extend datadate=tostring(payload.DATADATE)\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\n| extend logtype=tostring(payload.LOGTYPE) \n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results \n| extend cleaner_rules = parse_json(tostring(cleaner_results.rules))\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| extend execution_date = TimeGenerated\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_IN\n| extend dataset_name = dataset.NAME\n| mv-expand rules = cleaner_rules \n| mv-expand rule_list = rules \n| where MODULO_s == \"SANITED\" and logtype==\"END\" \n| where NIVEL_s == \"INFO\"\n| where app==\"$application\"\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\n| distinct tostring(dataset.NAME)"
   },
   { "name": "datadatefrom", "label": "From", "query": "2020/10/20" },
   { "name": "datadateto", "label": "To", "query": "2020/10/20" },
   { "name": "executiondate", "label": "ExecutionDate" }
  ]
 },
 "panels": [
  {
   "title": "Data Quality",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| extend logtype = tostring(payload.LOGTYPE)\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_IN\n| extend dataset_name = dataset.NAME\n| where MODULO_s == \"SANITED\"\r and logtype == \"END\" \n| where app==\"$application\"\r\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\r\n| where dataset_name in ($dataset)\r\n| project\nDATASET = tostring(dataset_name),\r\nEXECUTION_DATE=TimeGenerated,\r\nPERCENT_EXCLUDED=todouble(cleaner_results.percent_excluded)\r\n| summarize arg_max(EXECUTION_DATE, *) by DATASET\r\n| summarize (100-avg(PERCENT_EXCLUDED))\n",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Valid rows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend logtype = tostring(payload.LOGTYPE)\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_OUT\n| extend dataset_name = dataset.NAME\n| extend rows_valid = toint(dataset.NUM_ITEMS)\n| extend execution_date = TimeGenerated\n| where MODULO_s == \"SANITED\"\r and logtype == \"END\"\n| where app==\"$application\"\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\n| where execution_date == \"$executiondate\" or \"$executiondate\" == ''\n| where dataset_name in ($dataset)\n| project \r\nDATASET = tostring(dataset_name),\r\r\nEXECUTION_DATE=execution_date,\r\nROWS_VALID = rows_valid",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Ingested Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s) \r\n| extend region=tostring(payload.REGION) \r\n| extend app=tostring(payload.APPLICATION)\r\n| extend datadate=tostring(payload.DATADATE) \r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend logtype=tostring(payload.LOGTYPE) \r\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\r\n| extend execution_date = TimeGenerated\r\n| mv-expand dataset_array = lineage\r\n| mv-expand dataset = dataset_array.DATASETS_IN\r\n| mv-expand dataset_out = dataset_array.DATASETS_OUT\r\n| extend dataset_name = dataset.NAME\r\n| extend rows_in = toint(dataset.NUM_ITEMS)\r\n| extend rows_out = toint(dataset_out.NUM_ITEMS)\r\n| where MODULO_s == \"SANITED\" and logtype==\"END\" \r\n| where NIVEL_s == \"INFO\"\r\n| where app==\"$application\"\r\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\r\n| where execution_date == \"$executiondate\" or \"$executiondate\" == ''\r\n| where dataset_name in ($dataset)\r\n| order by execution_date asc\r\n| project \r\nAPPLICATION = app, \r\nREGION = region, \r\nDATASET = tostring(dataset_name), \r\nEXTRACTION_DATE = datadate, \r\nEXECUTION_DATE=execution_date,\r\nRAW = rows_in,\r\nSANITED = rows_out",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Not valid rows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend logtype = tostring(payload.LOGTYPE)\r\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\r\n| mv-expand dataset_array = lineage\r\n| mv-expand dataset = dataset_array.DATASETS_OUT\r\n| mv-expand dataset_in = dataset_array.DATASETS_IN\r\n| extend dataset_name = dataset.NAME\r\n| extend rows_valid = toint(dataset.NUM_ITEMS)\r\n| extend rows_in_raw = toint(dataset_in.NUM_ITEMS)\r\n| extend execution_date = TimeGenerated\r\n| where MODULO_s == \"SANITED\" and logtype == \"END\"\r\n| where app==\"$application\"\r\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\r\n| where execution_date == \"$executiondate\" or \"$executiondate\" == ''\r\n| where dataset_name in ($dataset)\r\n| project \r\nDATASET = tostring(dataset_name),\r\nEXECUTION_DATE=execution_date,\r\nROWS_INVALID = abs(rows_valid - rows_in_raw)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Unfulfilled Validation Rules",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s) \n| extend region=tostring(payload.REGION) \n| extend app=tostring(payload.APPLICATION)\n| extend datadate=tostring(payload.DATADATE)\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\n| extend logtype=tostring(payload.LOGTYPE) \n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results \n| extend cleaner_rules = iff(tostring(cleaner_results.rules) startswith \"[[\", cleaner_results.rules[0], cleaner_results.rules)\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| extend execution_date = TimeGenerated\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_IN\n| extend dataset_name = dataset.NAME\n| mv-expand rule_list = cleaner_rules \n| where MODULO_s == \"SANITED\" and logtype==\"END\" \n| where NIVEL_s == \"INFO\"\n| where app==\"$application\"\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\n| where execution_date == \"$executiondate\" or \"$executiondate\" == ''\n| where dataset_name in ($dataset)\n| order by execution_date asc\n| project \nAPPLICATION = app, \nREGION = region, \nDATASET = tostring(dataset_name), \nEXTRACTION_DATE = datadate, \nVALIDATION_MESSAGE = tostring(rule_list.msg), \nROWS_AFFECTED = tostring(rule_list.rows_excluded), \nLEVEL = tostring(rule_list.level), \nTOTAL_ROWS_AFFECTED=(todouble(rule_list.rows_excluded)/todouble(cleaner_results.total_row_excluded)), \nEXECUTION_DATE=execution_date",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Unfulfilled Validation Rules By Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate=todatetime(replace(\"/\",\"-\", datadate))\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend cleaner_rules = iff(tostring(cleaner_results.rules) startswith \"[[\", cleaner_results.rules[0], cleaner_results.rules)\r\n| extend execution_date = TimeGenerated\r\n| mv-expand rules = cleaner_rules\r\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\r\n| mv-expand dataset_array = lineage\r\n| mv-expand dataset = dataset_array.DATASETS_IN\r\n| extend dataset_name = dataset.NAME\r\n| extend logtype = tostring(payload.LOGTYPE)\r\n| where MODULO_s == \"SANITED\" and logtype == \"END\"\r\n| where app==\"$application\"\r\n| where tdatadate between(datetime(\"$datadatefrom\") .. datetime(\"$datadateto\"))\r\n| where execution_date == \"$executiondate\" or \"$executiondate\" == ''\r\n| where dataset_name in ($dataset)\r\n| order by execution_date asc\r\n| project\r\nVALIDATION_MESSAGE = tostring(rules.msg),\r\nROWS_AFFECTED = toint(rules.rows_excluded)\n| summarize sum(ROWS_AFFECTED) by VALIDATION_MESSAGE, now()\n",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Data Quality over Time By Dataset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend region=tostring(payload.REGION)\r\n| extend datadate=tostring(payload.DATADATE)\r\n| extend tdatadate = todatetime(replace(\"/\",\"-\", tostring(payload.DATADATE)))\r\n| extend app=tostring(payload.APPLICATION)\r\n| extend cleaner_results = parse_json(tostring(parse_json(payload.MSG))).cleaner_results\r\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| extend total_rows_excluded = toint(cleaner_results.total_row_excluded)\n| extend percent_excluded = todouble(cleaner_results.percent_excluded)\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_IN\n| extend dataset_name = dataset.NAME\n| extend logtype = tostring(payload.LOGTYPE) \n| where MODULO_s == \"SANITED\" and logtype == \"END\"\n| where region==\"$region\" and app==\"$application\" and dataset_name in ($dataset)\n| summarize arg_max(TimeGenerated, *) by datadate, tostring(dataset_name)\n| summarize sum(100-percent_excluded) by tostring(dataset_name), bin(tdatadate, $__interval)\n| sort by tdatadate asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Errores",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend app=tostring(parse_json(PAYLOAD_s).APPLICATION)\n| distinct app"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend region=tostring(parse_json(PAYLOAD_s).REGION)\n| distinct region"
   }
  ]
 },
 "panels": [
  {
   "title": "Errores por Uid",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\n| extend payload = parse_json(PAYLOAD_s)\n| extend region=tostring(payload.REGION)\n| extend app=tostring(payload.APPLICATION)\n| extend datadate=tostring(payload.DATADATE)\n| extend msg = tostring(payload.MSG)\n| extend status = tostring(payload.STATUS)\n| extend logtype = tostring(payload.LOGTYPE)\n| extend lineage = parse_json(tostring(parse_json(payload.LINEAGE_DATA)))\n| mv-expand dataset_array = lineage\n| mv-expand dataset = dataset_array.DATASETS_OUT\n| extend dataset_name = dataset.NAME\n| extend logtype = tostring(payload.LOGTYPE)\n| where region in ($Region) and app in ($Application)\r\n| where $__timeFilter(TimeGenerated) \r\n| where logtype in (\"ERROR\", \"END\") and status == \"KO\" \n| order by TimeGenerated, datadate asc\n| project \n EXECUTION_DATE=TimeGenerated,\n UID=UID_s,\n DATA_DATE=datadate,\n LOGTYPE=logtype,\n STATUS=tostring(status),\n MSG=tostring(msg)",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Errores totales por tipo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL     \n| extend payload = parse_json(PAYLOAD_s)\n| extend logtype=tostring(payload.LOGTYPE)\n| extend status=tostring(payload.STATUS)                                                                       \n| where $__timeFilter(TimeGenerated)\n| where logtype in (\"ERROR\", \"END\") and status == \"KO\"                \n| summarize count() by logtype, bin(TimeGenerated, $__interval) \n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Total Errores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL        \n| extend payload = parse_json(PAYLOAD_s)\n| extend logtype = tostring(payload.LOGTYPE)\n| extend status = tostring(payload.STATUS)                                                      //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                  //this is a macro used to show the full chart’s time range, choose the datetime column here\n| where logtype in (\"ERROR\", \"END\") and status == \"KO\" \n| summarize count()",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}
{
 "title": "Control de ejecuciones por fuente",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "UID", "label": "UID", "query": "*" },
   {
    "name": "Infra",
    "label": "Infra",
    "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL  \n| extend runsOn=tostring(parse_json(PAYLOAD_s).RUNS_ON)\n| distinct runsOn"
   }
  ]
 },
 "panels": [
  {
   "title": "Listado de tiempos de ejecución por fuente",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\n| extend logType=tostring(parse_json(PAYLOAD_s).LOGTYPE)\n| extend runsOn=tostring(parse_json(PAYLOAD_s).RUNS_ON)\n| where logType == 'END'\n| project endTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated\n| join kind = inner(CoreOperationLog#{LogWorkspaceEnv}#_CL\n | extend logType=tostring(parse_json(PAYLOAD_s).LOGTYPE)\n | extend runsOn=tostring(parse_json(PAYLOAD_s).RUNS_ON)\n | where logType == 'START'\n | project startTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated\n ) on uid\n| extend arr = split(uid,\"#\")\n| extend simpleUid = strcat_delim(\"#\", arr[0], arr[1])\n| where runsOn in ($Infra)\n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, uid) contains '$UID' or '*' == '$UID'\n| where $__timeFilter(TimeGenerated)\n| project uid, startTime, endTime, diff_seconds=datetime_diff('second', todatetime(endTime), todatetime(startTime)), runsOn, simpleUid\n| summarize TIEMPO_ACUMULADO_EN_SEGUNDOS=sum(diff_seconds) by UID=simpleUid, INFRA=runsOn",
      "resultFormat": "table",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Tiempos de ejecución por fuente en DATABRICKS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend logType=tostring(payload.LOGTYPE)\r\n| extend runsOn=tostring(payload.RUNS_ON)\r\n| where logType == 'END'\r\n| project endTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated, FECHA_s\r\n| join kind = inner(CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend logType=tostring(payload.LOGTYPE)\r\n| extend runsOn=tostring(payload.RUNS_ON)\r\n| where logType == 'START'\r\n| project startTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated\n) on uid\r\n| extend arr = split(uid,\"#\")\r\n| extend simpleUid = strcat_delim(\"#\", arr[0], arr[1])\r\n| extend tdatadate = todatetime(extract(\"(\\\\d{4}-\\\\d{2}-\\\\d{2}).*\", 1, FECHA_s))\r\n| where runsOn == \"DATABRICKS\"\r\n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, uid) contains '$UID' or '*' == '$UID'\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize TIEMPO_ACUMULADO_EN_SEGUNDOS=sum(datetime_diff('second', todatetime(endTime), todatetime(startTime))) by UID=simpleUid, tdatadate, bin(tdatadate, $__interval)\r\n| order by tdatadate asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  },
  {
   "title": "Tiempos de ejecución por fuente en ADF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend logType=tostring(payload.LOGTYPE)\r\n| extend runsOn=tostring(payload.RUNS_ON)\r\n| where logType == 'END'\r\n| project endTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated, FECHA_s\r\n| join kind = inner(CoreOperationLog#{LogWorkspaceEnv}#_CL\r\n| extend payload = parse_json(PAYLOAD_s)\r\n| extend logType=tostring(payload.LOGTYPE)\r\n| extend runsOn=tostring(payload.RUNS_ON)\r\n| where logType == 'START'\r\n| project startTime=todatetime(FECHA_s), uid=UID_s, logType, runsOn, TimeGenerated, payload\r\n) on uid\r\n| extend arr = split(uid,\"#\")\r\n| extend simpleUid = strcat_delim(\"#\", arr[0], arr[1])\r\n| extend tdatadate = todatetime(extract(\"(\\\\d{4}-\\\\d{2}-\\\\d{2}).*\", 1, FECHA_s))\r\n| where runsOn == \"ADF\"\r\n| where extract(\"^(.[^#]+)#([^#\\\\n]+)(#.*)*$\", 2, uid) contains '$UID' or '*' == '$UID'\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize TIEMPO_ACUMULADO_EN_SEGUNDOS=sum(datetime_diff('second', todatetime(endTime), todatetime(startTime))) by UID=simpleUid, tdatadate, bin(tdatadate, $__interval)\r\n| order by tdatadate asc",
      "resultFormat": "time_series",
      "workspace": "#{log-analytics-workspace-id}#"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "#{log-analytics-subscription-id}#"
    }
   ]
  }
 ]
}